### ISSUE TITLE
Span 

### ISSUE THREAD

**Issue by ImanGhader** [ImanGhader/temp#3]
I don't know how to span only some of the portfolio pieces on the home page. I want some pieces to span 2/3 and others 1/3. Currently it is doing that but the height of the workholder image is pushing every else down.

**Comment by lorefranko** [comment]
make cover photos for each portfolio campaign according to the size you wanted.

**Comment by padd0010** [comment]
It looks like it could be something about your list item styling/heights. They should be square like the image, but instead there's an extra 7px in the height. It could also be something with your grid units themselves.

**Comment by thomasjbradley** [comment]
I'm not entirely sure what you mean. Like the layout you have right now?

If you're trying to get everything to line up perfectly, it may be about the ratios. Since all the images are square, they may be not calculating out to the correct height and width ratios to fit into 3rds.

To @padd0010's point, the images need to have `display: block` on them to remove that little bit extra space at the bottom.
